# Controller Manager
apiVersion: v1
kind: Endpoints
metadata:
  name: kps-kube-prometheus-stack-kube-controller-manager
  namespace: kube-system
subsets:
  - addresses:
      - ip: 192.168.0.151
      - ip: 192.168.0.152
      - ip: 192.168.0.153
    ports:
      - name: http-metrics
        port: 10257
        protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kube-prometheus-stack-kube-controller-manager
  namespace: kube-system
subsets:
  - addresses:
      - ip: 192.168.0.151
      - ip: 192.168.0.152
      - ip: 192.168.0.153
    ports:
      - name: http-metrics
        port: 10257
        protocol: TCP
---
# Scheduler
apiVersion: v1
kind: Endpoints
metadata:
  name: kps-kube-prometheus-stack-kube-scheduler
  namespace: kube-system
subsets:
  - addresses:
      - ip: 192.168.0.151
      - ip: 192.168.0.152
      - ip: 192.168.0.153
    ports:
      - name: http-metrics
        port: 10259
        protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kube-prometheus-stack-kube-scheduler
  namespace: kube-system
subsets:
  - addresses:
      - ip: 192.168.0.151
      - ip: 192.168.0.152
      - ip: 192.168.0.153
    ports:
      - name: http-metrics
        port: 10259
        protocol: TCP
---
# Etcd
apiVersion: v1
kind: Endpoints
metadata:
  name: kps-kube-prometheus-stack-kube-etcd
  namespace: kube-system
subsets:
  - addresses:
      - ip: 192.168.0.151
      - ip: 192.168.0.152
      - ip: 192.168.0.153
    ports:
      - name: http-metrics
        port: 2381
        protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kube-prometheus-stack-kube-etcd
  namespace: kube-system
subsets:
  - addresses:
      - ip: 192.168.0.151
      - ip: 192.168.0.152
      - ip: 192.168.0.153
    ports:
      - name: http-metrics
        port: 2381
        protocol: TCP
---
# Proxy
apiVersion: v1
kind: Endpoints
metadata:
  name: kps-kube-prometheus-stack-kube-proxy
  namespace: kube-system
subsets:
  - addresses:
      - ip: 192.168.0.151
      - ip: 192.168.0.152
      - ip: 192.168.0.153
    ports:
      - name: http-metrics
        port: 10249
        protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kube-prometheus-stack-kube-proxy
  namespace: kube-system
subsets:
  - addresses:
      - ip: 192.168.0.151
      - ip: 192.168.0.152
      - ip: 192.168.0.153
    ports:
      - name: http-metrics
        port: 10249
        protocol: TCP
